export const content = {
  tr: {
    nav: {
      marketplace: 'Pazaryeri',
      why: 'Neden Carbonited?',
      contact: 'İletişim',
      login: 'Giriş Yap',
    },
    hero: {
      title: 'Kurumsal Karbon Kredilerini Tek Bir Platformda Alın, Satın ve İtfa Edin.',
      subtitle:
        'Dijital karbon kredileriyle aracısız, şeffaf ve anında işlem yapın. Küresel regülasyon uyumunuzu sağlayın ve net-sıfır hedeflerinize ulaşın.',
      cta: 'Projeleri Keşfet',
    },
    metrics: [
      { value: '2.5M+', label: 'Ton Doğrulanmış Kredi' },
      { value: '45+', label: 'Aktif İklim Projesi' },
      { value: '<$0.01', label: 'Ortalama İşlem Ücreti' },
      { value: '<3 Sn.', label: 'İtfa Süresi' },
    ],
    marketplace: {
      title: 'Doğrulanmış Küresel Karbon Projelerine Doğrudan Erişim',
      subtitle:
        'Sürdürülebilirlik hedeflerinize uygun, uluslararası standartlarda sertifikalandırılmış projeleri keşfedin.',
      cta: 'Tüm Projeleri İncele',
      cardCta: 'Detayları İncele',
      tonLabel: 'Mevcut Tonaj',
      priceLabel: 'Fiyat/Ton',
    },
    audience: {
      title: 'Carbonited Kimler İçin?',
      cards: [
        {
          title: 'Regülasyona Tabi Kurumlar (ETS & SKDM)',
          text: 'Emisyon Ticaret Sistemi (ETS) ve Sınırda Karbon Düzenleme Mekanizması (SKDM) kapsamında emisyonlarını yönetmek ve yasal uyum yükümlülüklerini yerine getirmek zorunda olan ağır sanayi, enerji ve ihracat şirketleri.',
        },
        {
          title: 'Gönüllü Karbon Alıcılar',
          text: 'Gönüllü karbon piyasasında ayak izini silerek çevresel sürdürülebilirlik (ESG) raporlarını güçlendirmek ve karbon nötr taahhütlerini yerine getirmek isteyen kurumlar.',
        },
        {
          title: 'Proje Geliştiricileri',
          text: 'Geliştirdikleri karbon azaltım ve uzaklaştırma projelerinden elde ettikleri kredileri aracı olmadan doğrudan küresel pazara sunmak isteyen tesis ve arazi sahipleri.',
        },
      ],
    },
    why: {
      title: 'Karbon Tedariğinde Yeni Standart',
      tabBuyers: 'Alıcılar İçin',
      tabSellers: 'Satıcılar İçin',
      buyersSubtitle: 'İhtiyacınız olan kredileri haftalar değil, saniyeler içinde bulun. Doğrulanmış projelere doğrudan erişim sağlayın.',
      sellersSubtitle: 'Çevresel etkinizi en yüksek değerle, anında gelire dönüştürün.',
      buyers: [
        { title: 'Uluslararası Sicil Entegrasyonu', text: 'Platformdaki tüm varlıklar, Verra ve Gold Standard gibi uluslararası siciller tarafından sertifikalandırılmış yüksek kaliteli projelerden oluşur.' },
        { title: 'Her Ölçekte Sorunsuz İşlem', text: 'İster 1 ton, ister 100.000 ton. Kurumsal karbon ihtiyaçlarınızı hiçbir gizli komisyon veya fiyat marjı olmadan saniyeler içinde karşılayın.' },
        { title: 'Tek Platform, Küresel Arz', text: 'Dünyanın dört bir yanındaki farklı metodolojilere sahip, onaylı iklim projelerini tek bir ekranda filtreleyin ve yönetin.' },
        { title: 'Çifte Harcama Koruması ve Anında İtfa', text: 'Kredileri geleneksel sicillerde bloke edip dijitalleştirerek mükerrer satışı kesin olarak engelliyoruz. Sıfır takas riskiyle saniyeler içinde itfa işlemi yapın ve doğrulanabilir sertifikanızı anında alın.' },
      ],
      sellers: [
        { title: 'Hızlı Dijitalleştirme ve Sıfır Listeleme Ücreti', text: 'Geleneksel sicillerdeki (VCS, GS vb.) varlıklarınızı saniyeler içinde platforma entegre edin. Ağır ön maliyetler ve listeleme ücretleri olmadan kredilerinizi anında dijitalleştirin.' },
        { title: 'Tam Fiyat Kontrolü ve Aracısız Ticaret', text: 'Satış koşullarınızı ve fiyatınızı hiçbir kısıtlama olmadan tamamen siz belirleyin. Gizli kesintiler olmadan, yarattığınız değerin tam karşılığını alın.' },
        { title: 'Tek Platform, Küresel Talep', text: 'Kredilerinizi bir kez listeleyin; pazar yerimiz üzerinden dünyanın dört bir yanındaki nitelikli kurumsal alıcılara anında ulaşın.' },
        { title: 'Anında Takas ve Güvenli Tahsilat', text: 'Geleneksel piyasaların yavaş ve belirsiz tahsilat süreçlerini geride bırakın. İşlem gerçekleştiği an sıfır takas riskiyle ödemenizi güvence altına alın ve saniyeler içinde kazancınızı tahsil edin.' },
      ],
    },
    dmrv: {
      title: 'Yapay Zeka ve Drone Destekli Karbon Ölçümü (dMRV)',
      tooltipTitle: 'Dijital Ölçüm, Raporlama ve Doğrulama',
      tooltip: 'Digital Measurement, Reporting and Verification (dMRV)',
      subtitle:
        'Henüz sertifikalandırılmamış bir iklim projeniz varsa, teknoloji partnerimizin dMRV altyapısından yararlanın. Uydu ve drone görüntülerini işleyen yapay zeka algoritmalarıyla sahanızın karbon tutma kapasitesini yüksek hassasiyetle ölçün ve uluslararası siciller için denetlenebilir dijital raporlara dönüştürün.',
      cta: 'Detayları İncele',
    },
    security: {
      title: 'Kurumsal Standartlarda Güvenlik ve Altyapı',
      cards: [
        { title: 'MPC ve HSM Destekli Saklama', text: 'Varlıklarınızı bankacılık standartlarındaki çok taraflı hesaplama (MPC) ve donanımsal güvenlik modülü (HSM) teknolojileriyle koruyoruz. Dağıtık anahtar mimarisi ile tek nokta hata riskini (SPOF) ortadan kaldırıyor, kesintisiz ve tam güvenli saklama sağlıyoruz.' },
        { title: 'Anında ve Risksiz Takas (DvP)', text: 'Finansal piyasa standardı olan DvP (teslimat karşılığı ödeme) altyapısıyla, varlık ve fon transferini eşzamanlı gerçekleştiriyoruz. İşlemlerin birbirine bağlı ve güvenli yapısı sayesinde takas riskini tamamen ortadan kaldırıyoruz.' },
        { title: 'Endüstri Standardı Akıllı Sözleşmeler ve KYB', text: 'Uluslararası karbon sicillerinde kayıtlı karbon kredileri, endüstri standardı olan ERC-20 akıllı sözleşmeleriyle dijital varlıklara dönüştürüyoruz. Platform güvenliğini ve yasal uyumluluğu korumak adına, pazar yerimizi yalnızca kurumsal kimlik doğrulama süreçlerini tamamlamış şirketlerin erişimine açıyoruz.' },
        { title: 'Tam Denetim İzi ve Rezerv Kanıtı', text: 'Platformumuzdaki her bir dijital karbon kredisinin, uluslararası sicillerdeki fiziksel sertifikalarla birebir eşleşmesini sağlıyoruz. Varlıkların tüm hareketleri Polygon ağı üzerinde değiştirilemez bir denetim izi olarak kaydedilir.' },
      ],
    },
    api: {
      title: 'Karbon Dengeleme Süreçlerinizi Otomatikleştirin',
      subtitle:
        'Otomatik karbon dengeleme özelliklerini operasyonlarınıza ve dijital ürünlerinize doğrudan entegre edin. Carbonited API; gerçek zamanlı piyasa verilerine erişmenize, doğrulanmış karbon kredilerini keşfetmenize ve satın alma/itfa işlemlerini programatik olarak gerçekleştirmenize olanak tanır.',
      cta: 'Demo Talep Edin',
    },
    homeContact: {
      title: 'Bize Ulaşın. Karbon Stratejinizi Birlikte Planlayalım.',
      name: 'Ad Soyad',
      email: 'Kurumsal E-posta',
      company: 'Şirket / Kurum Adı',
      solution: 'İlgilendiğiniz Çözüm',
      message: 'Mesajınız (İsteğe bağlı)',
      solutions: ['Karbon Kredisi Satın Almak', 'Proje Listelemek', 'dMRV Ölçüm Hizmeti', 'API ve Entegrasyon', 'Diğer'],
      submit: 'Talebi Gönder',
      note: 'Form demo amaçlıdır; talepler şu an kaydedilmemektedir.',
    },
    footer: { copy: '© 2026 Carbonited. Tüm hakları saklıdır.', privacy: 'Gizlilik', terms: 'Şartlar', contact: 'İletişim' },
    ui: {
      skipLink: 'İçeriğe atla',
      openMenu: 'Menüyü aç',
      closeMenu: 'Menüyü kapat',
      switchLang: 'Dili değiştir',
      breadcrumb: 'Sayfa yolu',
      select: 'Seçiniz',
      searchProjects: 'Proje ara',
      searchPlaceholder: 'Proje ara...',
      filtersAria: 'Filtreler',
      metricsAria: 'Platform metrikleri',
      formSuccess: 'Talebiniz alındı. En kısa sürede sizinle iletişime geçeceğiz.',
      mainNav: 'Ana menü',
      mobileNav: 'Mobil menü',
      footerNav: 'Alt menü',
    },
    common: {
      marketplace: 'Pazaryeri',
      projects: 'Karbon Projeleri',
      detail: 'Detay',
      purchase: 'Satın Al',
      portfolio: 'Portföy',
      myCredits: 'Karbon Kredilerim',
      primaryMarket: 'Birincil Piyasa',
      secondaryMarket: 'İkincil Piyasa',
      buyCredits: 'Karbon Kredisi Satın Al',
      totalVolume: 'Toplam Hacim',
      price: 'Fiyat',
      tokenPrice: 'Token Fiyatı',
      tokenCount: 'Token Adedi',
      maturity: 'Vade Süresi',
      vintage: 'Sertifika Yılı',
      goToMarketplace: 'Pazaryerine Git',
    },
    detail: {
      about: 'Proje Hakkında',
      tokenDetails: 'Proje ve Token Detayları',
      documents: 'Proje Belgeleri ve Raporlar',
      developer: 'Proje Geliştiricisi',
      verifier: 'Doğrulayıcı Kurum',
      sdgs: 'BM Kalkınma Amaçları (SDG)',
      totalCredits: 'Toplam Kredi (Ton CO2e)',
      vintage: 'Sertifika Yılı (Vintage)',
      registry: 'Proje Standardı / Registry',
      contract: 'Akıllı Kontrat Adresi',
      txHash: "İşlem Hash'i",
      methodology: 'Proje Metodolojisi',
      projectType: 'Proje Tipi ve Sektörü',
      docs: ['Proje Tasarım Belgesi (PDD).pdf', 'Doğrulama Raporu.pdf', 'İzleme Raporu.pdf'],
      sidebarPrimaryNote: 'Son oluşturulan tokenize varlıklarını görüntüleyebilirsiniz.',
      sidebarSecondaryNote: 'Kullanıcılar tarafından satışa sunulan karbon kredilerini görüntüleyebilirsiniz.',
      verifiedSeller: 'Doğrulanmış Satıcı Adresi',
      tokenTons: 'Token Adedi (Ton)',
    },
    purchase: {
      title: 'Karbon Kredisi Satın Al',
      confirm: 'İşlemi Onayla',
      projectName: 'Proje Adı',
      supply: 'Mevcut Arz (Ton CO2e)',
      conditions: 'Satın Alma Koşulları',
      conditionsText: 'Bu proje kapsamında tokenize edilmiş karbon kredileri, belirlenen minimum ve maksimum alım limitleri dahilinde satın alınabilir. Tüm işlemler blockchain üzerinde doğrulanır.',
      payAmount: 'Ödenecek Tutar',
      receiveAmount: 'Alınacak Miktar (Ton CO2e)',
      minCertPurchase: 'Sertifika Talebi İçin Min. Alım',
      minPurchase: 'Minimum Alım Miktarı',
      maxPurchase: 'Maksimum Alım Miktarı',
      wallet: 'Cüzdan Detayı',
      summary: 'İşlem Özeti',
      total: 'Toplam Tutar',
      unitPrice: 'Birim Fiyat',
      minPurchaseTon: 'Minimum Alım (Ton)',
      maxPurchaseTon: 'Maksimum Alım (Ton)',
      minCertCredit: 'Sertifika İçin Min. Kredi',
      exchangeRate: 'Kur Oranı',
      platformFee: 'Platform İşlem Ücreti',
      infraFee: 'Altyapı Ücreti',
      buyBtn: 'Krediyi Satın Al',
    },
    portfolio: {
      title: 'Portföyüm',
      categoryFilter: 'Proje Kategorisi',
      vintageFilter: 'Sertifika Yılı',
      statusFilter: 'Kredi Durumu',
      search: 'Ara',
      empty: 'Portföyünüzde henüz karbon kredisi bulunmuyor.',
      categories: ['Doğa Temelli', 'Yenilenebilir Enerji', 'Atık Yönetimi', 'Mavi Karbon'],
      statuses: ['Cüzdanda (Satılabilir)', 'Pazaryerinde Satışta'],
    },
    filters: [
      { value: 'all', label: 'Tümü' },
      { value: 'nature', label: 'Doğa Temelli' },
      { value: 'renewable', label: 'Yenilenebilir Enerji' },
      { value: 'blue', label: 'Mavi Karbon' },
      { value: 'waste', label: 'Atık Yönetimi' },
      { value: 'capture', label: 'Karbon Yakalama' },
    ],
    privacy: {
      title: 'Gizlilik Politikası',
      sections: [
        { heading: '1. Veri Sorumlusu', paragraphs: ['Carbonited (“biz”, “platform”) olarak kişisel verilerinizin güvenliğine önem veriyoruz. Bu politika, carbonited.com ve app.carbonited.com üzerinden toplanan verilerin nasıl işlendiğini açıklar.'] },
        { heading: '2. Toplanan Veriler', paragraphs: ['Hesap oluşturma, kimlik doğrulama ve işlem güvenliği için ad, soyad, e-posta, cüzdan adresi ve işlem geçmişi gibi veriler toplanabilir. Teknik loglar (IP, tarayıcı, cihaz) hizmet kalitesi için saklanır.'] },
        { heading: '3. Verilerin Kullanım Amacı', paragraphs: ['Verileriniz; platform hizmetlerinin sunulması, yasal yükümlülüklerin yerine getirilmesi, dolandırıcılık önleme, müşteri desteği ve ürün geliştirme amacıyla işlenir.'] },
        { heading: '4. Veri Paylaşımı', paragraphs: ['Kişisel verileriniz, yasal zorunluluklar veya açık rızanız dışında üçüncü taraflarla paylaşılmaz. Altyapı sağlayıcıları (hosting, analitik) yalnızca hizmet sunumu kapsamında veri işler.'] },
        { heading: '5. Haklarınız', paragraphs: ['KVKK kapsamında verilerinize erişim, düzeltme, silme ve işlemeye itiraz haklarına sahipsiniz. Talepleriniz için contact@carbonited.com adresine yazabilirsiniz.'] },
        { heading: '6. Güncellemeler', paragraphs: ['Bu politika zaman zaman güncellenebilir. Önemli değişiklikler sitede duyurulur. Son güncelleme: Mart 2026.'] },
      ],
    },
    terms: {
      title: 'Kullanım Şartları',
      sections: [
        { heading: '1. Kabul', paragraphs: ['Carbonited platformunu kullanarak bu şartları kabul etmiş sayılırsınız. Platform, tokenize karbon kredisi alım-satım ve portföy yönetimi hizmetleri sunar.'] },
        { heading: '2. Hizmet Kapsamı', paragraphs: ['Platform, doğrulanmış karbon kredi projelerinin listelenmesi, tokenizasyonu ve takasını kolaylaştırır. Carbonited, proje geliştiricisi değildir; aracı likidite katmanı olarak hizmet verir.'] },
        { heading: '3. Kullanıcı Yükümlülükleri', paragraphs: ['Hesap bilgilerinizin gizliliğinden siz sorumlusunuz. Yasalara uygun şekilde işlem yapmalı, yanlış veya yanıltıcı bilgi vermemelisiniz.'] },
        { heading: '4. Risk Bildirimi', paragraphs: ['Karbon kredisi ve dijital varlık işlemleri piyasa, düzenleyici ve teknoloji riskleri içerir. Geçmiş performans gelecek getiriyi garanti etmez.'] },
        { heading: '5. Fikri Mülkiyet', paragraphs: ['Carbonited markası, logosu ve platform içeriği telif hakkı ile korunmaktadır. İzinsiz kopyalama veya ticari kullanım yasaktır.'] },
        { heading: '6. Uygulanacak Hukuk', paragraphs: ['Bu şartlar Türkiye Cumhuriyeti kanunlarına tabidir. Uyuşmazlıklarda İstanbul mahkemeleri yetkilidir.'] },
      ],
    },
    contactPage: {
      title: 'İletişim',
      intro: 'Sorularınız, iş birliği teklifleri veya teknik destek için bize ulaşın.',
      general: 'Genel İletişim',
      enterprise: 'Kurumsal Satış',
      enterpriseDesc: 'B2B hacimli karbon kredisi alımları',
      projects: 'Proje Başvurusu',
      projectsDesc: 'Tokenize karbon projesi listeleme',
      platform: 'Platform Girişi',
      platformDesc: 'Mevcut hesabınızla işlem yapmak için:',
      hours: 'Hafta içi 09:00 – 18:00 (GMT+3)',
      formTitle: 'Mesaj Gönderin',
      name: 'Ad Soyad',
      namePlaceholder: 'Adınız Soyadınız',
      email: 'E-posta',
      emailPlaceholder: 'ornek@firma.com',
      subject: 'Konu',
      subjects: ['Genel Bilgi', 'Kurumsal Satış', 'Proje Başvurusu', 'Teknik Destek'],
      message: 'Mesajınız',
      messagePlaceholder: 'Mesajınızı yazın...',
      submit: 'Gönder',
      note: 'Form demo amaçlıdır; mesajlar şu an kaydedilmemektedir.',
      formSuccess: 'Mesajınız alındı. En kısa sürede dönüş yapacağız.',
    },
    seo: {
      homeTitle: 'Carbonited — Kurumsal Karbon Kredisi Pazaryeri',
      homeDescription: 'Dijital karbon kredilerini aracısız, şeffaf ve anında alın, satın ve itfa edin. Doğrulanmış küresel iklim projelerine doğrudan erişim.',
      portfolioTitle: 'Portföyüm — Karbon Kredilerim | Carbonited',
      portfolioDescription: 'Carbonited portföyünüzdeki tokenize karbon kredilerini yönetin.',
      privacyTitle: 'Gizlilik Politikası — Carbonited',
      privacyDescription: 'Carbonited gizlilik politikası. Kişisel verilerinizin nasıl toplandığı ve korunduğu.',
      termsTitle: 'Kullanım Şartları — Carbonited',
      termsDescription: 'Carbonited platform kullanım şartları ve hizmet koşulları.',
      contactTitle: 'İletişim — Carbonited',
      contactDescription: 'Carbonited ile iletişime geçin. Kurumsal satış, proje başvurusu ve teknik destek.',
      detailTitle: (title) => `${title} | Karbon Kredisi Projesi — Carbonited`,
      detailDescription: (p) => `${p.title} — ${p.developer} tarafından geliştirilen, ${p.verifier} doğrulamalı tokenize karbon kredisi. ${p.registry}, vintage ${p.vintage}.`,
      purchaseTitle: (title) => `${title} Karbon Kredisi Satın Al — Carbonited`,
      purchaseDescription: (p) => `${p.title} projesinden karbon kredisi satın alın. Min: ${p.minPurchase}, fiyat: ${p.price}.`,
    },
  },
  en: {
    nav: { marketplace: 'Marketplace', why: 'Why Carbonited?', contact: 'Contact', login: 'Sign In' },
    hero: {
      title: 'Buy, Sell, and Retire Corporate Carbon Credits in One Place',
      subtitle: 'Manage digital carbon credits with direct access, transparency, and instant settlement. Simplify global compliance and achieve your net-zero goals.',
      cta: 'View Projects',
    },
    metrics: [
      { value: '2.5M+', label: 'Tons of Verified Credits' },
      { value: '45+', label: 'Active Climate Projects' },
      { value: '<$0.01', label: 'Avg. Transaction Fee' },
      { value: '<3 Sec.', label: 'Retirement Time' },
    ],
    marketplace: {
      title: 'Direct Access to Verified Global Carbon Projects',
      subtitle: 'Discover internationally certified projects that align with your sustainability goals.',
      cta: 'Explore All Projects',
      cardCta: 'View Details',
      tonLabel: 'Available Tonnage',
      priceLabel: 'Price/Ton',
    },
    audience: {
      title: 'Who Is Carbonited For?',
      cards: [
        { title: 'Obligated Entities (ETS & CBAM)', text: 'Heavy industry, energy, and export companies required to manage compliance under ETS and CBAM regulations.' },
        { title: 'Voluntary Offtakers', text: 'Organizations aiming to offset their carbon footprint, enhance ESG scores, and meet net-zero commitments.' },
        { title: 'Carbon Originators', text: 'Facility and land owners selling credits from reduction and removal projects directly to the global market.' },
      ],
    },
    why: {
      title: 'The New Standard in Carbon Procurement',
      tabBuyers: 'For Buyers',
      tabSellers: 'For Sellers',
      buyersSubtitle: 'Find the credits you need in seconds, not weeks. Gain direct access to verified projects.',
      sellersSubtitle: 'Turn your environmental impact into maximum revenue, instantly.',
      buyers: [
        { title: 'Global Registry Integration', text: 'All credits are backed by high-quality projects certified by Verra and Gold Standard.' },
        { title: 'Frictionless Trading at Any Scale', text: 'From 1 to 100,000 tons, fulfill corporate carbon needs in seconds with no hidden fees.' },
        { title: 'Single Platform, Global Supply', text: 'Filter and manage verified climate projects across diverse methodologies from one dashboard.' },
        { title: 'Double Counting Protection & Instant Retirement', text: 'We prevent double counting by locking credits in source registries before digitizing them.' },
      ],
      sellers: [
        { title: 'Fast Digitization & Zero Listing Fees', text: 'Integrate assets from VCS, GS, and other registries in seconds with no listing fees.' },
        { title: 'Full Price Control & Direct Trading', text: 'Set your own sales terms and pricing without restrictions or hidden commissions.' },
        { title: 'Single Platform, Global Demand', text: 'List once and reach qualified corporate buyers worldwide through our marketplace.' },
        { title: 'Instant Settlement & Guaranteed Payouts', text: 'Leave behind the slow and opaque payment cycles of traditional markets. Secure your transaction with zero settlement risk and receive your payouts in seconds.' },
      ],
    },
    dmrv: {
      title: 'AI and Drone-Powered Carbon Measurement (dMRV)',
      tooltipTitle: 'Digital Measurement, Reporting and Verification',
      tooltip: 'Digital Measurement, Reporting and Verification (dMRV)',
      subtitle: 'Leverage our technology partner\'s dMRV infrastructure for your uncertified climate projects. Accurately measure your site\'s carbon sequestration capacity using AI algorithms that process satellite and drone imagery, and generate auditable digital reports for global registries.',
      cta: 'View Details',
    },
    security: {
      title: 'Enterprise-Grade Security & Infrastructure',
      cards: [
        { title: 'MPC & HSM-Backed Custody', text: 'Safeguard your assets with bank-grade Multi-Party Computation (MPC) and Hardware Security Modules (HSM). Our distributed key architecture eliminates single points of failure, delivering uninterrupted and fully secure custody.' },
        { title: 'Instant & Risk-Free Settlement (DvP)', text: 'Built on the financial market standard of Delivery versus Payment (DvP), our platform enables the simultaneous transfer of assets and funds. Settle transactions instantly with absolute certainty and zero settlement risk.' },
        { title: 'Industry-Standard Smart Contracts & KYB', text: 'Credits from global registries are converted into digital assets utilizing industry-standard ERC-20 smart contracts. Access to the marketplace is restricted exclusively to verified corporate entities.' },
        { title: 'Full Audit Trail & Proof of Reserves', text: 'Every digital carbon credit traded on the platform is backed 1:1 by physical certificates held in global registries. All asset movements are logged as an immutable audit trail on the Polygon network.' },
      ],
    },
    api: {
      title: 'Automate Your Carbon Offsetting',
      subtitle: 'Integrate automated carbon offsetting capabilities directly into your operations and digital products. Carbonited API enables seamless access to real-time market data, verified credit discovery, and programmatic execution of purchase and retirement transactions.',
      cta: 'Request a Demo',
    },
    homeContact: {
      title: "Get in Touch. Let's Shape Your Carbon Strategy Together.",
      name: 'Full name', email: 'Business email', company: 'Company / Organization name',
      solution: 'Solution of interest', message: 'Your message (Optional)',
      solutions: ['Carbon credit procurement', 'Project listing', 'dMRV services', 'API & integration', 'Other'],
      submit: 'Submit Request', note: 'This form is for demo purposes; submissions are not stored yet.',
    },
    footer: { copy: '© 2026 Carbonited. All rights reserved.', privacy: 'Privacy', terms: 'Terms', contact: 'Contact' },
    ui: {
      skipLink: 'Skip to content',
      openMenu: 'Open menu',
      closeMenu: 'Close menu',
      switchLang: 'Switch language',
      breadcrumb: 'Breadcrumb',
      select: 'Select',
      searchProjects: 'Search projects',
      searchPlaceholder: 'Search projects...',
      filtersAria: 'Filters',
      metricsAria: 'Platform metrics',
      formSuccess: 'Your request has been received. We will contact you shortly.',
      mainNav: 'Main navigation',
      mobileNav: 'Mobile navigation',
      footerNav: 'Footer navigation',
    },
    common: {
      marketplace: 'Marketplace',
      projects: 'Carbon Projects',
      detail: 'Details',
      purchase: 'Purchase',
      portfolio: 'Portfolio',
      myCredits: 'My Carbon Credits',
      primaryMarket: 'Primary Market',
      secondaryMarket: 'Secondary Market',
      buyCredits: 'Buy Carbon Credits',
      totalVolume: 'Total Volume',
      price: 'Price',
      tokenPrice: 'Token Price',
      tokenCount: 'Token Count',
      maturity: 'Maturity',
      vintage: 'Vintage Year',
      goToMarketplace: 'Go to Marketplace',
    },
    detail: {
      about: 'About the Project',
      tokenDetails: 'Project & Token Details',
      documents: 'Project Documents & Reports',
      developer: 'Project Developer',
      verifier: 'Verifying Body',
      sdgs: 'UN Sustainable Development Goals (SDG)',
      totalCredits: 'Total Credits (Ton CO2e)',
      vintage: 'Vintage Year',
      registry: 'Project Standard / Registry',
      contract: 'Smart Contract Address',
      txHash: 'Transaction Hash',
      methodology: 'Project Methodology',
      projectType: 'Project Type & Sector',
      docs: ['Project Design Document (PDD).pdf', 'Verification Report.pdf', 'Monitoring Report.pdf'],
      sidebarPrimaryNote: 'View the most recently tokenized assets.',
      sidebarSecondaryNote: 'View carbon credits listed for sale by users.',
      verifiedSeller: 'Verified Seller Address',
      tokenTons: 'Token Amount (Tons)',
    },
    purchase: {
      title: 'Buy Carbon Credits',
      confirm: 'Confirm Transaction',
      projectName: 'Project Name',
      supply: 'Available Supply (Ton CO2e)',
      conditions: 'Purchase Terms',
      conditionsText: 'Tokenized carbon credits under this project can be purchased within the defined minimum and maximum limits. All transactions are verified on the blockchain.',
      payAmount: 'Amount to Pay',
      receiveAmount: 'Amount to Receive (Ton CO2e)',
      minCertPurchase: 'Min. Purchase for Certificate',
      minPurchase: 'Minimum Purchase',
      maxPurchase: 'Maximum Purchase',
      wallet: 'Wallet Details',
      summary: 'Transaction Summary',
      total: 'Total Amount',
      unitPrice: 'Unit Price',
      minPurchaseTon: 'Minimum Purchase (Tons)',
      maxPurchaseTon: 'Maximum Purchase (Tons)',
      minCertCredit: 'Min. Credits for Certificate',
      exchangeRate: 'Exchange Rate',
      platformFee: 'Platform Fee',
      infraFee: 'Infrastructure Fee',
      buyBtn: 'Buy Credits',
    },
    portfolio: {
      title: 'My Portfolio',
      categoryFilter: 'Project Category',
      vintageFilter: 'Vintage Year',
      statusFilter: 'Credit Status',
      search: 'Search',
      empty: 'You do not have any carbon credits in your portfolio yet.',
      categories: ['Nature-Based', 'Renewable Energy', 'Waste Management', 'Blue Carbon'],
      statuses: ['In Wallet (Sellable)', 'Listed on Marketplace'],
    },
    filters: [
      { value: 'all', label: 'All' },
      { value: 'nature', label: 'Nature-Based' },
      { value: 'renewable', label: 'Renewable Energy' },
      { value: 'blue', label: 'Blue Carbon' },
      { value: 'waste', label: 'Waste Management' },
      { value: 'capture', label: 'Carbon Capture' },
    ],
    privacy: {
      title: 'Privacy Policy',
      sections: [
        { heading: '1. Data Controller', paragraphs: ['At Carbonited (“we”, “the platform”), we take the security of your personal data seriously. This policy explains how data collected via carbonited.com and app.carbonited.com is processed.'] },
        { heading: '2. Data Collected', paragraphs: ['We may collect name, email, wallet address, and transaction history for account creation, identity verification, and transaction security. Technical logs (IP, browser, device) are stored for service quality.'] },
        { heading: '3. Purpose of Processing', paragraphs: ['Your data is processed to provide platform services, fulfill legal obligations, prevent fraud, offer customer support, and improve our products.'] },
        { heading: '4. Data Sharing', paragraphs: ['Personal data is not shared with third parties except where required by law or with your explicit consent. Infrastructure providers (hosting, analytics) process data only to deliver services.'] },
        { heading: '5. Your Rights', paragraphs: ['You have the right to access, rectify, delete, and object to processing of your data. Contact us at contact@carbonited.com for requests.'] },
        { heading: '6. Updates', paragraphs: ['This policy may be updated from time to time. Material changes will be announced on the site. Last updated: March 2026.'] },
      ],
    },
    terms: {
      title: 'Terms of Service',
      sections: [
        { heading: '1. Acceptance', paragraphs: ['By using the Carbonited platform, you agree to these terms. The platform provides tokenized carbon credit trading and portfolio management services.'] },
        { heading: '2. Scope of Service', paragraphs: ['The platform facilitates listing, tokenization, and trading of verified carbon credit projects. Carbonited is not a project developer; it operates as an intermediary liquidity layer.'] },
        { heading: '3. User Obligations', paragraphs: ['You are responsible for keeping your account credentials secure. You must transact in compliance with applicable laws and must not provide false or misleading information.'] },
        { heading: '4. Risk Disclosure', paragraphs: ['Carbon credit and digital asset transactions involve market, regulatory, and technology risks. Past performance does not guarantee future returns.'] },
        { heading: '5. Intellectual Property', paragraphs: ['The Carbonited brand, logo, and platform content are protected by copyright. Unauthorized copying or commercial use is prohibited.'] },
        { heading: '6. Governing Law', paragraphs: ['These terms are governed by the laws of the Republic of Türkiye. Istanbul courts have jurisdiction over disputes.'] },
      ],
    },
    contactPage: {
      title: 'Contact',
      intro: 'Reach out for questions, partnership proposals, or technical support.',
      general: 'General Inquiries',
      enterprise: 'Enterprise Sales',
      enterpriseDesc: 'B2B bulk carbon credit procurement',
      projects: 'Project Applications',
      projectsDesc: 'List your tokenized carbon project',
      platform: 'Platform Login',
      platformDesc: 'Trade with your existing account:',
      hours: 'Weekdays 09:00 – 18:00 (GMT+3)',
      formTitle: 'Send a Message',
      name: 'Full name',
      namePlaceholder: 'Your name',
      email: 'Email',
      emailPlaceholder: 'you@company.com',
      subject: 'Subject',
      subjects: ['General Inquiry', 'Enterprise Sales', 'Project Application', 'Technical Support'],
      message: 'Your message',
      messagePlaceholder: 'Write your message...',
      submit: 'Send',
      note: 'This form is for demo purposes; messages are not stored yet.',
      formSuccess: 'Your message has been received. We will get back to you shortly.',
    },
    seo: {
      homeTitle: 'Carbonited — Corporate Carbon Credit Marketplace',
      homeDescription: 'Buy, sell, and retire digital carbon credits with direct access, transparency, and instant settlement. Verified global climate projects in one place.',
      portfolioTitle: 'My Portfolio — Carbon Credits | Carbonited',
      portfolioDescription: 'Manage tokenized carbon credits in your Carbonited portfolio.',
      privacyTitle: 'Privacy Policy — Carbonited',
      privacyDescription: 'Carbonited privacy policy. How your personal data is collected and protected.',
      termsTitle: 'Terms of Service — Carbonited',
      termsDescription: 'Carbonited platform terms of service and conditions.',
      contactTitle: 'Contact — Carbonited',
      contactDescription: 'Contact Carbonited. Enterprise sales, project applications, and technical support.',
      detailTitle: (title) => `${title} | Carbon Credit Project — Carbonited`,
      detailDescription: (p) => `${p.title} — tokenized carbon credit project developed by ${p.developer}, verified by ${p.verifier}. ${p.registry}, vintage ${p.vintage}.`,
      purchaseTitle: (title) => `Buy ${title} Carbon Credits — Carbonited`,
      purchaseDescription: (p) => `Purchase carbon credits from ${p.title}. Min: ${p.minPurchase}, price: ${p.price}.`,
    },
  },
};

export function getContent(lang = getLang()) {
  return content[lang];
}

export const showcaseProjects = [
  { id: 'turkiye-ruzgar', title: { tr: 'Soma Rüzgar Enerjisi Santrali', en: 'Soma Wind Power Plant' }, desc: { tr: 'Ulusal şebekeye temiz enerji sağlayarak fosil yakıt bağımlılığını azaltan yüksek kapasiteli rüzgar tesisi...', en: 'High-capacity wind facility reducing fossil fuel dependency by providing clean energy to the national grid...' }, tonnage: '2,500', price: '$4.50', image: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=800&h=500&q=80' },
  { id: 'karadeniz-orman', title: { tr: 'Karadeniz Orman Restorasyonu', en: 'Black Sea Forest Restoration' }, desc: { tr: 'Bozulmuş orman alanlarının yeniden ağaçlandırılması ve karbon tutulumunun artırılması.', en: 'Reforestation project restoring degraded forest areas and increasing carbon sequestration.' }, tonnage: '8,200', price: '$6.50', image: 'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=800&h=500&q=80' },
  { id: 'ege-gunes', title: { tr: 'Ege Güneş Enerjisi Santrali', en: 'Aegean Solar Power Plant' }, desc: { tr: 'Güneş enerjisi ile fosil yakıt tüketimini azaltan ve şebekeye temiz enerji sağlayan santral.', en: 'Solar plant reducing fossil fuel consumption and supplying clean energy to the grid.' }, tonnage: '15,000', price: '$3.80', image: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&w=800&h=500&q=80' },
  { id: 'marmara-mavi', title: { tr: 'Marmara Mavi Karbon Koruma', en: 'Marmara Blue Carbon Protection' }, desc: { tr: 'Kıyı ekosistemlerinin korunması ve mavi karbon rezervlerinin sürdürülebilir yönetimi.', en: 'Coastal ecosystem protection and sustainable management of blue carbon reserves.' }, tonnage: '6,340', price: '$5.40', image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=800&h=500&q=80' },
];

export function getLang() {
  return localStorage.getItem('carbonited-lang') === 'en' ? 'en' : 'tr';
}

export function setLang(lang) {
  localStorage.setItem('carbonited-lang', lang);
}
