function pick(field, lang) {
  if (field && typeof field === 'object' && (field.tr || field.en)) {
    return field[lang] || field.tr;
  }
  return field;
}

export const categories = [
  { label: { tr: 'Doğa Temelli Çözümler', en: 'Nature-Based Solutions' }, slug: 'nature', image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&h=400&fit=crop' },
  { label: { tr: 'Yenilenebilir Enerji', en: 'Renewable Energy' }, slug: 'renewable', image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&h=400&fit=crop' },
  { label: { tr: 'Karbon Yakalama', en: 'Carbon Capture' }, slug: 'capture', image: '/images/category-capture.svg' },
  { label: { tr: 'Atık Yönetimi', en: 'Waste Management' }, slug: 'waste', image: '/images/category-waste.svg' },
  { label: { tr: 'Mavi Karbon', en: 'Blue Carbon' }, slug: 'blue', image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=600&h=400&fit=crop' },
];

export const filters = [
  { value: 'all', label: { tr: 'Tümü', en: 'All' } },
  { value: 'nature', label: { tr: 'Doğa Temelli', en: 'Nature-Based' } },
  { value: 'renewable', label: { tr: 'Yenilenebilir Enerji', en: 'Renewable Energy' } },
  { value: 'blue', label: { tr: 'Mavi Karbon', en: 'Blue Carbon' } },
  { value: 'waste', label: { tr: 'Atık Yönetimi', en: 'Waste Management' } },
  { value: 'capture', label: { tr: 'Karbon Yakalama', en: 'Carbon Capture' } },
];

const rawProjects = [
  {
    id: 'turkiye-ruzgar',
    title: { tr: 'Türkiye Rüzgar Enerjisi Projesi', en: 'Turkey Wind Energy Project' },
    category: 'renewable',
    market: 'primary',
    volume: '₺10.452.512',
    price: '₺800',
    tokens: '130.000.000',
    maturity: '24 Ay',
    vintage: '2024',
    supply: '500.000 tCO2e',
    image: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=400&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=1200&h=600&fit=crop',
    developer: 'Aperam BioEnergia',
    verifier: 'Earthood Services',
    sdgs: { tr: '13 (İklim Eylemi), 7 (Temiz Enerji), 8 (İnsana Yakışır İş)', en: '13 (Climate Action), 7 (Clean Energy), 8 (Decent Work)' },
    description: {
      tr: 'Bu proje, Türkiye\'nin rüzgar potansiyelini kullanarak fosil yakıt tüketimini engellemeyi amaçlamaktadır. Tokenize edilen her kredi, bağımsız doğrulama kuruluşları tarafından onaylanmış fiziksel karbon varlıklarını temsil eder.',
      en: 'This project aims to reduce fossil fuel consumption by harnessing Turkey\'s wind potential. Each tokenized credit represents physical carbon assets verified by independent validation bodies.',
    },
    registry: 'Verra / VCS',
    contractAddress: '0x7a3f...9c2e',
    txHash: '0x4b8d...1f7a',
    methodology: 'ACM0002',
    projectType: { tr: 'Azaltım / Yenilenebilir Enerji', en: 'Reduction / Renewable Energy' },
    minPurchase: '1.000 tCO2e',
    maxPurchase: '50.000 tCO2e',
    minCertificate: '500 tCO2e',
    exchangeRate: '1 Token = ₺800',
    platformFee: '₺120',
    infraFee: '₺45',
    sellerAddress: '0x9f2a...4d8b',
  },
  {
    id: 'karadeniz-orman',
    title: { tr: 'Karadeniz Orman Restorasyonu', en: 'Black Sea Forest Restoration' },
    category: 'nature',
    market: 'primary',
    volume: '₺8.210.000',
    price: '₺650',
    tokens: '95.000.000',
    maturity: '36 Ay',
    vintage: '2023',
    supply: '320.000 tCO2e',
    image: 'https://images.unsplash.com/photo-1511497584788-876760111969?w=400&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1511497584788-876760111969?w=1200&h=600&fit=crop',
    developer: 'GreenForest AG',
    verifier: 'SCS Global Services',
    sdgs: { tr: '13 (İklim Eylemi), 15 (Karasal Yaşam)', en: '13 (Climate Action), 15 (Life on Land)' },
    description: {
      tr: 'Karadeniz bölgesindeki bozulmuş orman alanlarının restorasyonu ve karbon tutulumunun artırılması hedeflenmektedir.',
      en: 'This project targets restoration of degraded forest areas in the Black Sea region and increased carbon sequestration.',
    },
    registry: 'Gold Standard',
    contractAddress: '0x3c1e...8a4f',
    txHash: '0x2d9c...6e3b',
    methodology: 'VM0007',
    projectType: { tr: 'Doğa Temelli / Orman', en: 'Nature-Based / Forestry' },
    minPurchase: '500 tCO2e',
    maxPurchase: '30.000 tCO2e',
    minCertificate: '250 tCO2e',
    exchangeRate: '1 Token = ₺650',
    platformFee: '₺95',
    infraFee: '₺35',
    sellerAddress: '0x5b7c...2a1f',
  },
  {
    id: 'ege-gunes',
    title: { tr: 'Ege Güneş Enerjisi Santrali', en: 'Aegean Solar Power Plant' },
    category: 'renewable',
    market: 'secondary',
    volume: '₺15.780.000',
    price: '₺920',
    tokens: '210.000.000',
    maturity: '18 Ay',
    vintage: '2024',
    supply: '180.000 tCO2e',
    image: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=400&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=1200&h=600&fit=crop',
    developer: 'SolarEge Ltd.',
    verifier: 'TÜV SÜD',
    sdgs: { tr: '7 (Temiz Enerji), 13 (İklim Eylemi)', en: '7 (Clean Energy), 13 (Climate Action)' },
    description: {
      tr: 'Ege bölgesinde kurulan güneş enerjisi santrali ile fosil yakıt tüketiminin azaltılması sağlanmaktadır.',
      en: 'A solar power plant in the Aegean region reduces fossil fuel consumption and supplies clean energy.',
    },
    registry: 'Verra / VCS',
    contractAddress: '0x8d4f...3b7c',
    txHash: '0x6a2e...9d1f',
    methodology: 'AMS-I.D.',
    projectType: { tr: 'Azaltım / Yenilenebilir Enerji', en: 'Reduction / Renewable Energy' },
    minPurchase: '2.000 tCO2e',
    maxPurchase: '100.000 tCO2e',
    minCertificate: '1.000 tCO2e',
    exchangeRate: '1 Token = ₺920',
    platformFee: '₺150',
    infraFee: '₺55',
    sellerAddress: '0x1e8a...7c4d',
  },
  {
    id: 'marmara-mavi',
    title: { tr: 'Marmara Mavi Karbon Koruma', en: 'Marmara Blue Carbon Protection' },
    category: 'blue',
    market: 'primary',
    volume: '₺6.340.000',
    price: '₺540',
    tokens: '72.000.000',
    maturity: '48 Ay',
    vintage: '2022',
    supply: '95.000 tCO2e',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=600&fit=crop',
    developer: 'BlueCarbon Initiative',
    verifier: 'Verra',
    sdgs: { tr: '14 (Sudaki Yaşam), 13 (İklim Eylemi)', en: '14 (Life Below Water), 13 (Climate Action)' },
    description: {
      tr: 'Marmara Denizi kıyı şeridindeki mavi karbon ekosistemlerinin korunması ve restorasyonu.',
      en: 'Protection and restoration of blue carbon ecosystems along the Marmara Sea coastline.',
    },
    registry: 'Verra / VCS',
    contractAddress: '0x2f6b...5e9a',
    txHash: '0x9c3d...4f2e',
    methodology: 'VM0033',
    projectType: { tr: 'Mavi Karbon / Koruma', en: 'Blue Carbon / Conservation' },
    minPurchase: '300 tCO2e',
    maxPurchase: '20.000 tCO2e',
    minCertificate: '150 tCO2e',
    exchangeRate: '1 Token = ₺540',
    platformFee: '₺80',
    infraFee: '₺30',
    sellerAddress: '0x4a1d...8f6c',
  },
  {
    id: 'istanbul-atik',
    title: { tr: 'İstanbul Atık Dönüşüm Tesisi', en: 'Istanbul Waste Conversion Facility' },
    category: 'waste',
    market: 'secondary',
    volume: '₺4.920.000',
    price: '₺480',
    tokens: '58.000.000',
    maturity: '30 Ay',
    vintage: '2023',
    supply: '75.000 tCO2e',
    image: '/images/category-waste.svg',
    heroImage: '/images/category-waste.svg',
    developer: 'EcoWaste TR',
    verifier: 'DNV',
    sdgs: { tr: '12 (Sorumlu Üretim), 13 (İklim Eylemi)', en: '12 (Responsible Consumption), 13 (Climate Action)' },
    description: {
      tr: 'Organik atıkların biyogaz dönüşümü ile metan emisyonlarının azaltılması projesi.',
      en: 'A project reducing methane emissions through biogas conversion of organic waste.',
    },
    registry: 'Gold Standard',
    contractAddress: '0x6e2c...1d8f',
    txHash: '0x3b7a...6c4e',
    methodology: 'AMS-III.D.',
    projectType: { tr: 'Atık Yönetimi / Azaltım', en: 'Waste Management / Reduction' },
    minPurchase: '400 tCO2e',
    maxPurchase: '25.000 tCO2e',
    minCertificate: '200 tCO2e',
    exchangeRate: '1 Token = ₺480',
    platformFee: '₺70',
    infraFee: '₺25',
    sellerAddress: '0x7d3f...2b9a',
  },
  {
    id: 'anadolu-biyokutle',
    title: { tr: 'Anadolu Biyokütle Enerji Projesi', en: 'Anatolia Biomass Energy Project' },
    category: 'renewable',
    market: 'primary',
    volume: '₺7.650.000',
    price: '₺710',
    tokens: '88.000.000',
    maturity: '24 Ay',
    vintage: '2024',
    supply: '110.000 tCO2e',
    image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=400&h=400&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=1200&h=600&fit=crop',
    developer: 'BioEnergy Anadolu',
    verifier: 'SGS',
    sdgs: { tr: '7 (Temiz Enerji), 8 (İnsana Yakışır İş), 13 (İklim Eylemi)', en: '7 (Clean Energy), 8 (Decent Work), 13 (Climate Action)' },
    description: {
      tr: 'Tarımsal atıklardan biyokütle enerjisi üretimi ile sürdürülebilir enerji sağlanması.',
      en: 'Sustainable energy production from agricultural waste through biomass energy generation.',
    },
    registry: 'Verra / VCS',
    contractAddress: '0x9a4e...7c3b',
    txHash: '0x5f1d...8a6c',
    methodology: 'ACM0006',
    projectType: { tr: 'Azaltım / Yenilenebilir Enerji', en: 'Reduction / Renewable Energy' },
    minPurchase: '800 tCO2e',
    maxPurchase: '40.000 tCO2e',
    minCertificate: '400 tCO2e',
    exchangeRate: '1 Token = ₺710',
    platformFee: '₺105',
    infraFee: '₺40',
    sellerAddress: '0x3c8b...5e2f',
  },
];

function localizeProject(p, lang) {
  return {
    ...p,
    title: pick(p.title, lang),
    description: pick(p.description, lang),
    sdgs: pick(p.sdgs, lang),
    projectType: pick(p.projectType, lang),
  };
}

export const projects = rawProjects.map((p) => localizeProject(p, 'tr'));

export function getProject(id, lang = 'tr') {
  const raw = rawProjects.find((p) => p.id === id) || rawProjects[0];
  return localizeProject(raw, lang);
}

export function getProjects(lang = 'tr') {
  return rawProjects.map((p) => localizeProject(p, lang));
}

export function getFilters(lang = 'tr') {
  return filters.map((f) => ({ value: f.value, label: pick(f.label, lang) }));
}
